### ISSUE TITLE
Fix `github_api` helper to use `BUILDKITE_REPO`

### ISSUE THREAD

**Issue by wzieba** [Automattic/bash-cache-buildkite-plugin#125]
- it should use `BUILDKITE_REPO` instead of `BUILDKITE_PULL_REQUEST_REPO` because we want to communicate with GitHub API not necessarily on a PR-associated branch 
- probably use regex expression from https://github.com/Automattic/a8c-ci-toolkit-buildkite-plugin/pull/124/files#diff-704b8fc3d47317b87aeb9552bfa16ec27caf723ccf9380e72fe508b6c7c6c207R7-R11 to determine repo owner and name. It supports both `https` and `git@` coordinates

**Comment by AliSoftware** [comment]
@wzieba Ah, I missed this, I already made a PR to fix it in #127 😅 

We could recycle this issue to instead say "adopt `github_api` helper in `upload_sarif_to_github` implementation instead though, as #127 didn't cover that, and I'm guessing you probably only want to look at that once you've confirmed your initial issue on `trunk` branch of client repos?  🤷 
Or if you update `upload_sarif_to_github` right away we can keep this issue closed and done; whatever you prefer.
